#!/usr/bin/env bash
#
# Copyright 2016-2024 Rene Widera
#
# This file is part of PIConGPU.
#
# PIConGPU is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PIConGPU is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PIConGPU.
# If not, see <http://www.gnu.org/licenses/>.
#

# search recursive inside a folder if the keyword `__global__` is used.
# Alternatively '"-"' as first argument will search the files given on stdin
# (one per line) instead, using a single batched grep.
# @param $1 path to the folder, or "-" to read a list of files from stdin
# @result 0 if keyword is not found else 1

folderName=$1

if [ "$folderName" = "-" ] ; then
    mapfile -t fileList
else
    mapfile -t fileList < <(find "$folderName" -type f)
fi

result=`grep -nH "__global__" "${fileList[@]}"`
if [ $? -eq 0 ] ; then
    echo "Not allowed keyword __global__ found in the following files:" >&2
    echo "$result" | cut -f1-2 -d":" >&2
    exit 1
fi
exit 0
