#!/usr/bin/env bash
#
# Copyright 2016-2024 Axel Huebl, Rene Widera
#
# This file is part of PIConGPU.
#
# PIConGPU is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PIConGPU is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PIConGPU.
# If not, see <http://www.gnu.org/licenses/>.
#

# search recursive inside the `$1` folder if a file is using the
# wrong doxygen keyword `\$2` (e.g. `\param` instead of `@param`).
# The check runs as a single batched grep over all candidate files.
# Alternatively '"-"' as first argument will search the files given on stdin
# (one per line) instead.
#
# @param $1 path to the folder, or "-" to read a list of files from stdin
# @param $2 doxygen keyword without the leading backslash e.g param
# @result 0 if no files are found, else 1

folderName=$1
keyword=$2

if [ "$folderName" = "-" ] ; then
    mapfile -t candidates
else
    pattern="\.def$|\.h$|\.cpp$|\.cu$|\.hpp$|\.tpp$|\.kernel$|\.loader$|"\
"\.param$|\.unitless$"

    mapfile -t candidates < <(find "$folderName" \
        -not -path "./.git/*" \
        -type f | \
        grep -P "${pattern}")
fi

ok=0
files=()

for i in $(grep -l "\\\\${keyword}" "${candidates[@]}" || true)
do
    files+=($i)
    echo "$i uses \\${keyword} instead of @$keyword"
    ok=1
done

if [ $ok -ne 0 ]
then
    echo ""
    echo "SUMMARY"
    echo "-------"
    echo "Run the following command(s) on the above files to update your style:"
    echo ""
    for i in ${files[@]}
    do
        echo "sed -i 's/\\\\${keyword}/@${keyword}/g' $i"
    done
fi

exit $ok
